{% set name = "yaqd-pololu" %}
{% set version = "2023.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd_pololu-{{ version }}.tar.gz
  sha256: ff5a0e00b33b6c9c47f21a600f2bd00ff1b3c7575a006210d7ae336e4f082c01

build:
  entry_points:
    - yaqd-pololu-ticcmd = yaqd_pololu._pololu_ticcmd:PololuTicCMD.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7
    - yaqd-core >=2023.6.0
    - pyyaml

test:
  imports:
    - yaqd_pololu
  commands:
    - pip check
    - yaqd-pololu-ticcmd --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: Daemons for Pololu motor controllers.
  dev_url: https://github.com/yaq-project/yaqd-pololu
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ddkohler
